### ISSUE TITLE
Поддержка opencart 2.0

### ISSUE THREAD

**Issue by znvPredatoR** [shaman/opencart-hotline-export#1]
Привет, я добавил поддержку версии 2.0. Правда она без обратной совместимости, может создать отдельную ветку?

**Comment by shaman** [comment]
Конечно!

**Comment by znvPredatoR** [comment]
Сделал, но не дает сделать push. Видимо, нужны права.

**Comment by shaman** [comment]
Вместо Push, сделайте Pull Request

**Comment by znvPredatoR** [comment]
Сделал. Но я могу только в master его сделать, это перетрет все существующие файлы. Там не обратной совместимости с 1.5

**Comment by znvPredatoR** [comment]
Может стоит создать у вас отдельную ветку opencart-2.0, например и я туда сделаю pull request?

**Comment by shaman** [comment]
Все правильно, изменения добавлены в актуальную версию master.
Для более ранней 1.5 создана отдельная ветка, по которой принимаются пулы из соотв. форка.

Спасибо за инициативу, добавлю в анонс на сайте сообщества.
